/**
 * @constructor
 * @class ErrorName
 */
function ErrorName() {
	//
}

// Common
ErrorName.EVAL_ERROR = "EVAL_ERROR";
ErrorName.INTERNAL_ERROR = "INTERNAL_ERROR";
ErrorName.RANGE_ERROR = "RANGE_ERROR";
ErrorName.REFERENCE_ERROR = "REFERENCE_ERROR";
ErrorName.SYNTAX_ERROR = "SYNTAX_ERROR";
ErrorName.TYPE_ERROR = "TYPE_ERROR";
ErrorName.URI_ERROR = "URI_ERROR";

ErrorName.ATTEMPT_MODIFY_LOCKED_DATA = "ATTEMPT_MODIFY_LOCKED_DATA";

// Undo
ErrorName.UNCLOSED_UNDO_GROUP = "UNCLOSED_UNDO_GROUP";
ErrorName.NO_UNDO_GROUP = "NO_UNDO_GROUP";

// File
ErrorName.FILE_MISSING = "FILE_MISSING";
ErrorName.FOLDER_MISSING = "FOLDER_MISSING";
ErrorName.FAILED_CREATE_FILE = "FAILED_CREATE_FILE";
ErrorName.FAILED_CREATE_FOLDER = "FAILED_CREATE_FOLDER";

// Import
ErrorName.FAILED_IMPORT_ITEM = "FAILED_IMPORT_ITEM";

// AE App
ErrorName.AE_NO_FILES_ACCESS = "AE_NO_FILES_ACCESS";
ErrorName.AE_UNSUPPORTED_VERSION = "AE_UNSUPPORTED_VERSION";

// Init
ErrorName.NOT_INITIALIZED = "NOT_INITIALIZED";
ErrorName.ALREADY_INITIALIZED = "ALREADY_INITIALIZED";
ErrorName.SINGLETON_VIOLATION = "SINGLETON_VIOLATION";
ErrorName.NOT_IMPLEMENTED_INTERFACE = "NOT_IMPLEMENTED_INTERFACE";

// Assert
ErrorName.CUSTOM_CONDITION = "CUSTOM_CONDITION";
ErrorName.TYPE_MISMATCH = "TYPE_MISMATCH";
ErrorName.INSTANCEOF_MISMATCH = "INSTANCEOF_MISMATCH";
ErrorName.STRING_LENGTH = "STRING_LENGTH";
ErrorName.STRING_REG_EXP = "STRING_REG_EXP";
ErrorName.NUMBER_RANGE = "NUMBER_RANGE";
ErrorName.STRING_ENVATO_ID = "STRING_ENVATO_ID";
ErrorName.STRING_VERSION = "STRING_VERSION";
ErrorName.STRING_ITEM_INDEX = "STRING_ITEM_INDEX";
ErrorName.STRING_ITEM_ID = "STRING_ITEM_ID";
ErrorName.STRING_NAME = "STRING_NAME";
ErrorName.STRING_WORD = "STRING_WORD";
ErrorName.STRING_CONTAINS = "STRING_CONTAINS";
ErrorName.ONE_OF = "ONE_OF";

// Item
ErrorName.LAYER_MISSING = "LAYER_MISSING";
ErrorName.EFFECT_MISSING = "EFFECT_MISSING";

// Verification
ErrorName.INVALID_PURCHASE_CODE = "INVALID_PURCHASE_CODE";
ErrorName.CONNECTION_ERROR = "CONNECTION_ERROR";